# Generated by Django 5.1.1 on 2024-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_location_description_alter_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
