# Generated by Django 5.1.2 on 2024-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0006_alter_worker_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm10_min", models.FloatField()),
                ("pm10_max", models.FloatField()),
                ("pm25_min", models.FloatField()),
                ("pm25_max", models.FloatField()),
                ("pm1_min", models.FloatField()),
                ("pm1_max", models.FloatField()),
                ("o2_min", models.FloatField()),
                ("o2_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("temperature_max", models.FloatField()),
                ("humidity_min", models.FloatField()),
                ("humidity_max", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="pm10_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="pm1_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="pm25_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="sos",
            field=models.BooleanField(default=False),
        ),
    ]
