# Generated by Django 5.1.2 on 2024-11-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0007_safelevels_location_humidity_location_pm10_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
