# Generated by Django 5.1.2 on 2024-11-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0008_worker_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
