# Generated by Django 5.1.2 on 2024-11-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0009_location_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="aadhar",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
