# Generated by Django 5.1.2 on 2024-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0010_worker_aadhar"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
