name: Deploy to Web Server

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Write SSH key to file
        run: echo "${{ secrets.SSH_GCP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        shell: bash

      - name: Set permissions for the SSH key
        run: chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add SSH key to ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        shell: bash

      - name: SSH into server, stash changes, and git pull
        run: |
          ssh -o StrictHostKeyChecking=no hushraj@35.207.243.179 '
            cd subsecure_django_api
            git pull
            sudo docker-compose up --build -d
          '
          echo "Allowing Django Program to start properly"
          echo "Entering into sleep for 10 seconds.. Kindly wait..."
          sleep 10

      - name: Check API Status with Retry
        run: |
          for i in {1..3}; do
            RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null https://api-dev.subsecure.in/)
            if [ "$RESPONSE" -eq 404 ]; then
              echo "API is up and running!"
              exit 0
            else
              echo "API returned status code $RESPONSE, retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "API failed to start after multiple attempts"
